language: ruby
deploy:
  provider: s3
  access_key_id: AKIAJPYBICCEUDOZDRTQ
  secret_access_key:
    secure: BeqQLscDl2slmxuaMGOV+xvdUx2wgdqlMBI2nne9d8DeDmxPMzmIduRcKhkHv8wTDsRLuKFzqw6IjSjVk54VSAKdNfI2lgodW3PidWJILJ++FcpHx7LuJpJur/Jq+dMPJGcINa75lD+q++V0ErBRBjfSWLvUvluqRJxzvhT/QMo=
  bucket: deploy.magnetic.io
  upload-dir: modules
  local-dir: target
  region: eu-west-1
  endpoint: s3-eu-west-1.amazonaws.com
  skip_cleanup: true
  on:
    repo: tnolet/vamp_dashboard
